# Chapter 10 - Hacking Optimus

## Using a local installation of Optimus

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("../../../optimus")

Use Vaex

In [3]:
from optimus import Optimus
op = Optimus("vaex")

In [ ]:
op.client

In [5]:
# df = op.load.my_csv("foo.csv") # <-- you can create this function

df = op.load.csv("foo.csv") # <-- already implemented on Optimus core

In [6]:
df.cols.names()

['name', 'function', ' phone_number', 'num']

## Basic class functions

In [7]:
df.cols.upper("name") # <-- already implemented on Optimus core, compatible with Vaex

name        function                  phone_number                  num
(string)    (string)                 (string)                 (float64)
----------  -----------------------  ---------------------  -----------
OPTIMUS     leader                   123-456-7890                   2.2
BUMBLEBEE   espionage                123-456-7890                   3
EJECT       ELECTRONIC SURVEILLANCE  optimus@cybertron.com          4

In [8]:
df.cols.select("name")

name
(string)
----------
Optimus
Bumblebee
eject

In [9]:
df.cols.slice("name", start=1, stop=3) # <-- already implemented on Optimus core

name        function                  phone_number                  num
(string)    (string)                 (string)                 (float64)
----------  -----------------------  ---------------------  -----------
pt          leader                   123-456-7890                   2.2
um          espionage                123-456-7890                   3
je          ELECTRONIC SURVEILLANCE  optimus@cybertron.com          4

## Numeric transformations

In [10]:
df.cols.min("num")

array(2.2)

In [11]:
df.cols.sin("num")["num"]

        num
  (float64)
-----------
   0.808496
   0.14112
  -0.756802

In [12]:
# example

import numpy as np
import vaex as vx

def sin_plus(expression, value): # <-- Can be implemented as a method in 'VaexFunctions' class
    return np.sin(expression) + value

df.cols.apply("num", func=sin_plus, args=(1,))

name        function                  phone_number                  num
(string)    (string)                 (string)                 (float64)
----------  -----------------------  ---------------------  -----------
Optimus     leader                   123-456-7890              1.8085
Bumblebee   espionage                123-456-7890              1.14112
eject       ELECTRONIC SURVEILLANCE  optimus@cybertron.com     0.243198

## Applying functions

In [13]:
def func(value):
    return value + 10

df.cols.apply("num", func, mode="map")["num"]  # <-- Applied to every element

        num
  (float64)
-----------
       12.2
       13
       14

In [14]:
def func(expression_or_series):
    return expression_or_series + 10

df.cols.apply("num", func, mode="vectorized")["num"] # <-- Applied to the whole Vaex expression

        num
  (float64)
-----------
       12.2
       13
       14